# Getting Started

In [1]:
import numpy as np

Let;s create some arrays

In [4]:
my_list = list(range(11))

In [5]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [6]:
type(my_list)

list

In [7]:
my_array = np.array(my_list)

In [8]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
type(my_array)

numpy.ndarray

What can I learn about this array?

In [10]:
my_array.dtype

dtype('int64')

In [11]:
my_array2 = np.array([2.3, 3.14, 6.5])

In [12]:
my_array2.dtype

dtype('float64')

In [13]:
my_array3 = np.array([2.3, 'hello'])

In [14]:
my_array3.dtype

dtype('<U32')

## 'Special' Arrays

In [15]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [17]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
# hmmmmm
np.array_equal(np.ones(10), np.empty(10))

True

be careful with empty arrays

In [27]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
my_array.reshape(11,1).shape

(11, 1)

In [28]:
my_array.reshape(1,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [38]:
my_array4 = np.array([2.3, 3.14, 6.5, 9.0])

In [ ]:
my_array4

In [39]:
my_array4.reshape(2,2)

array([[2.3 , 3.14],
       [6.5 , 9.  ]])

In [42]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.random.random((5,5))

array([[0.86663725, 0.5839132 , 0.79057475, 0.19819089, 0.66842676],
       [0.2549704 , 0.37366031, 0.82169576, 0.8719664 , 0.14361331],
       [0.35594769, 0.66065965, 0.8308316 , 0.60724484, 0.18002813],
       [0.49182235, 0.53025611, 0.99142941, 0.63526253, 0.60475124],
       [0.24822275, 0.21837077, 0.92467923, 0.11453467, 0.38457404]])

In [47]:
np.random.random?

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method


In [49]:
np.random.randint(0,10, (3,4))

array([[3, 5, 4, 8],
       [8, 6, 8, 7],
       [0, 4, 3, 9]])

In [50]:
np.random.normal(loc = 0, scale= 3, size = (3,3))

array([[ 1.85082203,  5.55193529, -0.79767139],
       [ 0.22530285, -3.69541793,  1.85980308],
       [ 6.08953592, -1.60262535,  0.43614706]])

In [45]:
np.linspace(0,10,num=10, endpoint = False)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Array Indexing

how do i access certain elements of the array?

In [57]:
np.random.seed(1234567890)
my_matrix = np.random.normal(loc = 0, scale = 3, size = (5,3))

In [53]:
my_matrix

array([[ 4.02049037,  5.21277368,  4.49696503],
       [-0.68593   ,  6.093102  ,  6.51097484],
       [ 4.78935795, -2.30835467,  1.69817471],
       [-0.35781054, -0.43953241, -2.39671013],
       [ 2.31549834, -2.48457408,  3.98002448]])

In [55]:
my_matrix[0,0]

4.020490373155893

In [56]:
my_matrix[3,1]

-0.4395324139559934

In [59]:
my_matrix[:,0]

array([ 4.02049037, -0.68593   ,  4.78935795, -0.35781054,  2.31549834])

In [62]:
my_matrix[0,0:2]

array([4.02049037, 5.21277368])

In [63]:
my_matrix[0,0]

4.020490373155893

In [64]:
my_matrix[0,0] = 30

In [65]:
my_matrix

array([[30.        ,  5.21277368,  4.49696503],
       [-0.68593   ,  6.093102  ,  6.51097484],
       [ 4.78935795, -2.30835467,  1.69817471],
       [-0.35781054, -0.43953241, -2.39671013],
       [ 2.31549834, -2.48457408,  3.98002448]])

In [66]:
my_matrix2 = my_matrix

In [67]:
my_matrix2

array([[30.        ,  5.21277368,  4.49696503],
       [-0.68593   ,  6.093102  ,  6.51097484],
       [ 4.78935795, -2.30835467,  1.69817471],
       [-0.35781054, -0.43953241, -2.39671013],
       [ 2.31549834, -2.48457408,  3.98002448]])

In [68]:
my_matrix[0,0] = 100

In [70]:
my_matrix

array([[100.        ,   5.21277368,   4.49696503],
       [ -0.68593   ,   6.093102  ,   6.51097484],
       [  4.78935795,  -2.30835467,   1.69817471],
       [ -0.35781054,  -0.43953241,  -2.39671013],
       [  2.31549834,  -2.48457408,   3.98002448]])

In [71]:
my_matrix2

array([[100.        ,   5.21277368,   4.49696503],
       [ -0.68593   ,   6.093102  ,   6.51097484],
       [  4.78935795,  -2.30835467,   1.69817471],
       [ -0.35781054,  -0.43953241,  -2.39671013],
       [  2.31549834,  -2.48457408,   3.98002448]])

In [80]:
my_matrix3 = my_matrix.

AttributeError: 'numpy.ndarray' object has no attribute 'deepcopy'

## Operations on Arrays

In [84]:
a = np.array([1,2,5,6]).reshape(2,2)

In [85]:
a

array([[1, 2],
       [5, 6]])

In [87]:
b = np.array([1,2,3,4]).reshape(2,2)
c = np.array([1,2,3,4,5,6]).reshape(3,2)

In [89]:
a - b

array([[0, 0],
       [2, 2]])

In [90]:
a + c

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [91]:
a**2

array([[ 1,  4],
       [25, 36]])

In [92]:
a @ b

array([[ 7, 10],
       [23, 34]])

In [93]:
np.dot(a,b)

array([[ 7, 10],
       [23, 34]])

In [94]:
np.linalg.inv(a) # slow but works

array([[-1.5 ,  0.5 ],
       [ 1.25, -0.25]])

In [ ]:
# More array indexing

a

In [95]:
a

array([[1, 2],
       [5, 6]])

In [96]:
a > 3

array([[False, False],
       [ True,  True]])

In [103]:
a[(a > 3) &  (a < 6)]

array([5])

In [104]:
a > 3 

array([[False, False],
       [ True,  True]])

In [106]:
a < 6

array([[ True,  True],
       [ True, False]])

In [ ]:
# main point: & is element wise, 'and' is not

In [74]:
my_matrix[0,1] = 54

In [76]:
my_matrix

array([[100.        ,  54.        ,   4.49696503],
       [ -0.68593   ,   6.093102  ,   6.51097484],
       [  4.78935795,  -2.30835467,   1.69817471],
       [ -0.35781054,  -0.43953241,  -2.39671013],
       [  2.31549834,  -2.48457408,   3.98002448]])

In [78]:
my_matrix3

array([[100.        ,  54.        ,   4.49696503],
       [ -0.68593   ,   6.093102  ,   6.51097484],
       [  4.78935795,  -2.30835467,   1.69817471],
       [ -0.35781054,  -0.43953241,  -2.39671013],
       [  2.31549834,  -2.48457408,   3.98002448]])

In [43]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
my_array.shape

(11,)